import os
import smtplib
import streamlit as st

from email.mime.text import MIMEText
from dotenv import load_dotenv


load_dotenv()


try:

    EMAIL = (

        st.secrets.get(

            "EMAIL"

        )

        or

        os.getenv(

            "EMAIL"

        )

    )


    EMAIL_PASSWORD = (

        st.secrets.get(

            "EMAIL_PASSWORD"

        )

        or

        os.getenv(

            "EMAIL_PASSWORD"

        )

    )


except:


    EMAIL = os.getenv(

        "EMAIL"

    )


    EMAIL_PASSWORD = os.getenv(

        "EMAIL_PASSWORD"

    )


def create_monthly_report(

    username,

    total,

    budget,

    saved,

    prediction

):


    status = (

        "Healthy"

        if saved >= 0

        else

        "Overspent"

    )


    color = (

        "#10B981"

        if saved >= 0

        else

        "#EF4444"

    )


    insight = (

        "Excellent savings habits. Keep investing."

        if saved >= 0

        else

        "Reduce non-essential spending."

    )


    html = f"""

<html>


<body style="

background:#f4f7fc;

padding:30px;

font-family:Arial;

">


<div style="

max-width:700px;

margin:auto;

background:white;

border-radius:24px;

overflow:hidden;

box-shadow:

0 10px 30px rgba(

0,

0,

0,

0.15

);

">


<!-- HEADER -->


<div style="

padding:35px;

background:

linear-gradient(

135deg,

#4f46e5,

#2563eb

);

color:white;

text-align:center;

">


<h1>

📊 Expense Report

</h1>


<p>

AI Financial Tracker

</p>


</div>



<div style="padding:30px;">


<h2>

Hello {username} 👋

</h2>


<p>

Here is your monthly finance report.

</p>


<table width="100%">


<tr>


<td style="padding:10px">


<div style="

background:#f8fafc;

padding:20px;

border-radius:16px;

text-align:center;

">


<h3>

💸 Total

</h3>


<h2>

₹{total:.0f}

</h2>


</div>


</td>



<td style="padding:10px">


<div style="

background:#f8fafc;

padding:20px;

border-radius:16px;

text-align:center;

">


<h3>

🎯 Budget

</h3>


<h2>

₹{budget:.0f}

</h2>


</div>


</td>


</tr>




<tr>


<td style="padding:10px">


<div style="

background:#f8fafc;

padding:20px;

border-radius:16px;

text-align:center;

">


<h3>

💰 Saved

</h3>


<h2>

₹{saved:.0f}

</h2>


</div>


</td>



<td style="padding:10px">


<div style="

background:#f8fafc;

padding:20px;

border-radius:16px;

text-align:center;

">


<h3>

🔮 Prediction

</h3>


<h2>

₹{prediction:.0f}

</h2>


</div>


</td>


</tr>


</table>



<br>



<div style="

padding:18px;

background:{color};

border-radius:16px;

color:white;

font-size:18px;

text-align:center;

">


Budget Status:

<strong>

{status}

</strong>


</div>



<br>



<div style="

background:#eef2ff;

padding:20px;

border-radius:16px;

">


<h3>

🤖 AI Insight

</h3>


<p>

{insight}

</p>


</div>



<br>



<div style="

padding:20px;

border-left:

6px solid #4f46e5;

background:

#f8fafc;

">


<h3>

Recommendation

</h3>


<p>


{

"Continue current spending patterns."

if saved >= 0

else

"Reduce unnecessary purchases."

}


</p>


</div>



</div>




<div style="

background:#111827;

padding:25px;

color:white;

text-align:center;

">


Generated by

<strong>

AI Expense Tracker

</strong>


<br>


Track • Save • Predict • Grow


</div>



</div>


</body>


</html>


"""


    return html




def send_email(

    recipient,

    subject,

    message

):


    try:


        msg = MIMEText(

            message,

            "html"

        )


        msg["Subject"] = subject

        msg["From"] = EMAIL

        msg["To"] = recipient


        server = smtplib.SMTP(

            "smtp.gmail.com",

            587

        )


        server.starttls()


        server.login(

            EMAIL,

            EMAIL_PASSWORD

        )


        server.sendmail(

            EMAIL,

            recipient,

            msg.as_string()

        )


        server.quit()


        return True


    except Exception as e:


        print(

            "EMAIL ERROR:",

            e

        )


        return False
